using System.Text;
using Frapper.Core.Domain.Plan;
using Frapper.Core.Domain.Plan.Ops;
using Frapper.Core.Domain.Schema;

namespace Frapper.EFMigrationEmitter;

public static class SqlMigrationEmitter
{
    public static string Emit(MigrationPlan plan)
    {
        var sb = new StringBuilder();

        sb.AppendLine("-- Auto-generated by Frapper");
        sb.AppendLine("-- Review before applying in production");
        sb.AppendLine();

        foreach (var op in plan.Up)
        {
            switch (op)
            {
                case CreateTableOp createTable:
                    EmitCreateTable(sb, createTable.Table);
                    break;

                case AddColumnOp addColumn:
                    EmitAddColumn(sb, addColumn);
                    break;

                case AlterColumnOp alterColumn:
                    EmitAlterColumn(sb, alterColumn);
                    break;

                case DropColumnOp dropColumn:
                    EmitDropColumn(sb, dropColumn);
                    break;

                case DropTableOp dropTable:
                    sb.AppendLine($"-- DROP TABLE [{dropTable.Schema}].[{dropTable.Name}];");
                    sb.AppendLine();
                    break;

                default:
                    sb.AppendLine($"-- Unsupported operation: {op.Kind}");
                    sb.AppendLine();
                    break;
            }
        }

        return sb.ToString();
    }

    private static void EmitCreateTable(StringBuilder sb, DbTable table)
    {
        sb.AppendLine($"CREATE TABLE [{table.Schema}].[{table.Name}]");
        sb.AppendLine("(");

        for (int i = 0; i < table.Columns.Count; i++)
        {
            var column = table.Columns[i];
            var suffix = i < table.Columns.Count - 1 || table.PrimaryKey is not null ? "," : string.Empty;

            sb.Append("    ");
            sb.Append(ColumnDefinition(column));
            sb.AppendLine(suffix);
        }

        if (table.PrimaryKey is not null)
        {
            var pkColumns = string.Join(", ", table.PrimaryKey.Columns.Select(c => $"[{c}]"));
            var clustered = table.PrimaryKey.IsClustered ? "CLUSTERED" : "NONCLUSTERED";

            sb.AppendLine(
                $"    CONSTRAINT [{table.PrimaryKey.Name}] PRIMARY KEY {clustered} ({pkColumns})");
        }

        sb.AppendLine(");");
        sb.AppendLine();
    }

    private static void EmitAddColumn(StringBuilder sb, AddColumnOp op)
    {
        sb.AppendLine(
            $"ALTER TABLE [{op.Schema}].[{op.Table}] ADD {ColumnDefinition(op.Column)};");
        sb.AppendLine();
    }

    private static void EmitAlterColumn(StringBuilder sb, AlterColumnOp op)
    {
        sb.AppendLine(
            $"ALTER TABLE [{op.Schema}].[{op.Table}] ALTER COLUMN {ColumnDefinitionWithoutDefault(op.New)};");
        sb.AppendLine();

        if (!string.Equals(op.Old.DefaultSql, op.New.DefaultSql, StringComparison.Ordinal))
        {
            sb.AppendLine($"-- Default constraint changed for [{op.Schema}].[{op.Table}].[{op.New.Name}]");
            sb.AppendLine("-- Manual review may be required.");
            sb.AppendLine();
        }
    }

    private static void EmitDropColumn(StringBuilder sb, DropColumnOp op)
    {
        sb.AppendLine($"ALTER TABLE [{op.Schema}].[{op.Table}] DROP COLUMN [{op.Column}];");
        sb.AppendLine();
    }

    private static string ColumnDefinition(DbColumn column)
    {
        var sb = new StringBuilder();

        sb.Append($"[{column.Name}] {FormatSqlType(column.Type)}");

        if (column.IsIdentity)
            sb.Append(" IDENTITY(1,1)");

        sb.Append(column.IsNullable ? " NULL" : " NOT NULL");

        if (!string.IsNullOrWhiteSpace(column.DefaultSql))
            sb.Append($" DEFAULT {column.DefaultSql}");

        return sb.ToString();
    }

    private static string ColumnDefinitionWithoutDefault(DbColumn column)
    {
        var sb = new StringBuilder();

        sb.Append($"[{column.Name}] {FormatSqlType(column.Type)}");

        if (column.IsIdentity)
            sb.Append(" IDENTITY(1,1)");

        sb.Append(column.IsNullable ? " NULL" : " NOT NULL");

        return sb.ToString();
    }

    private static string FormatSqlType(SqlType type)
    {
        return type.StoreType switch
        {
            "nvarchar" or "varchar" or "char" or "nchar" or "varbinary" or "binary"
                => $"{type.StoreType}({(type.Length is null ? "max" : type.Length)})",

            "decimal" or "numeric"
                => $"{type.StoreType}({type.Precision ?? 18},{type.Scale ?? 0})",

            "datetime2" or "datetimeoffset" or "time"
                => type.Precision is not null
                    ? $"{type.StoreType}({type.Precision})"
                    : type.StoreType,

            _ => type.StoreType
        };
    }
}