using System.Text;
using Frapper.Core.Domain.Plan;
using Frapper.Core.Domain.Plan.Ops;
using Frapper.Core.Domain.Schema;

namespace Frapper.EFMigrationEmitter;

public static class SqlMigrationEmitter
{
    public static string Emit(MigrationPlan plan)
    {
        var sb = new StringBuilder();

        sb.AppendLine("-- Auto-generated by Frapper");
        sb.AppendLine("-- Review before applying in production");
        sb.AppendLine("SET XACT_ABORT ON;");
        sb.AppendLine();

        foreach (var op in plan.Up)
        {
            switch (op)
            {
                case CreateTableOp createTable:
                    EmitCreateTable(sb, createTable.Table);
                    break;

                case AddColumnOp addColumn:
                    EmitAddColumn(sb, addColumn);
                    break;

                case AlterColumnOp alterColumn:
                    EmitAlterColumn(sb, alterColumn);
                    break;

                case DropColumnOp dropColumn:
                    EmitDropColumn(sb, dropColumn);
                    break;

                case DropTableOp dropTable:
                    EmitDropTable(sb, dropTable);
                    break;

                default:
                    sb.AppendLine($"-- Unsupported operation: {op.Kind}");
                    sb.AppendLine();
                    break;
            }
        }

        return sb.ToString();
    }

    private static void EmitCreateTable(StringBuilder sb, DbTable table)
    {
        sb.AppendLine($"CREATE TABLE {FullTableName(table.Schema, table.Name)}");
        sb.AppendLine("(");

        for (int i = 0; i < table.Columns.Count; i++)
        {
            var column = table.Columns[i];
            var suffix = i < table.Columns.Count - 1 || table.PrimaryKey is not null ? "," : string.Empty;

            sb.Append("    ");
            sb.Append(ColumnDefinition(column));
            sb.AppendLine(suffix);
        }

        if (table.PrimaryKey is not null)
        {
            var pkColumns = string.Join(", ", table.PrimaryKey.Columns.Select(Bracket));
            var clustered = table.PrimaryKey.IsClustered ? "CLUSTERED" : "NONCLUSTERED";

            sb.AppendLine(
                $"    CONSTRAINT {Bracket(table.PrimaryKey.Name)} PRIMARY KEY {clustered} ({pkColumns})");
        }

        sb.AppendLine(");");
        sb.AppendLine();
    }

    private static void EmitAddColumn(StringBuilder sb, AddColumnOp op)
    {
        sb.AppendLine(
            $"ALTER TABLE {FullTableName(op.Schema, op.Table)} ADD {ColumnDefinition(op.Column)};");
        sb.AppendLine();
    }

    private static void EmitAlterColumn(StringBuilder sb, AlterColumnOp op)
    {
        if (op.Old.IsIdentity != op.New.IsIdentity)
        {
            sb.AppendLine($"-- WARNING: IDENTITY change detected for {FullColumnName(op.Schema, op.Table, op.New.Name)}");
            sb.AppendLine("-- SQL Server does not support changing IDENTITY with a simple ALTER COLUMN.");
            sb.AppendLine("-- Manual migration may be required.");
            sb.AppendLine();
            return;
        }

        if (!string.Equals(op.Old.DefaultSql, op.New.DefaultSql, StringComparison.Ordinal))
        {
            sb.AppendLine($"-- WARNING: DEFAULT constraint change detected for {FullColumnName(op.Schema, op.Table, op.New.Name)}");
            sb.AppendLine("-- Manual migration may be required because SQL Server default constraints may have generated names.");
            sb.AppendLine();
        }

        sb.AppendLine(
            $"ALTER TABLE {FullTableName(op.Schema, op.Table)} ALTER COLUMN {ColumnDefinitionWithoutDefault(op.New)};");
        sb.AppendLine();
    }

    private static void EmitDropColumn(StringBuilder sb, DropColumnOp op)
    {
        var tableName = FullTableName(op.Schema, op.Table);
        var columnName = Bracket(op.Column);

        sb.AppendLine("DECLARE @df_name sysname;");
        sb.AppendLine("SELECT @df_name = dc.name");
        sb.AppendLine("FROM sys.default_constraints dc");
        sb.AppendLine("INNER JOIN sys.columns c");
        sb.AppendLine("    ON c.object_id = dc.parent_object_id");
        sb.AppendLine("   AND c.column_id = dc.parent_column_id");
        sb.AppendLine("INNER JOIN sys.tables t");
        sb.AppendLine("    ON t.object_id = c.object_id");
        sb.AppendLine("INNER JOIN sys.schemas s");
        sb.AppendLine("    ON s.schema_id = t.schema_id");
        sb.AppendLine($"WHERE s.name = '{EscapeSqlLiteral(op.Schema)}'");
        sb.AppendLine($"  AND t.name = '{EscapeSqlLiteral(op.Table)}'");
        sb.AppendLine($"  AND c.name = '{EscapeSqlLiteral(op.Column)}';");
        sb.AppendLine();

        sb.AppendLine("IF @df_name IS NOT NULL");
        sb.AppendLine($"    EXEC('ALTER TABLE {tableName} DROP CONSTRAINT [' + @df_name + ']');");
        sb.AppendLine();

        sb.AppendLine($"ALTER TABLE {tableName} DROP COLUMN {columnName};");
        sb.AppendLine();
    }

    private static void EmitDropTable(StringBuilder sb, DropTableOp op)
    {
        sb.AppendLine($"DROP TABLE {FullTableName(op.Schema, op.Name)};");
        sb.AppendLine();
    }

    private static string ColumnDefinition(DbColumn column)
    {
        var sb = new StringBuilder();

        sb.Append($"{Bracket(column.Name)} {FormatSqlType(column.Type)}");

        if (column.IsIdentity)
            sb.Append(" IDENTITY(1,1)");

        sb.Append(column.IsNullable ? " NULL" : " NOT NULL");

        if (!string.IsNullOrWhiteSpace(column.DefaultSql))
            sb.Append($" DEFAULT {column.DefaultSql}");

        return sb.ToString();
    }

    private static string ColumnDefinitionWithoutDefault(DbColumn column)
    {
        var sb = new StringBuilder();

        sb.Append($"{Bracket(column.Name)} {FormatSqlType(column.Type)}");

        if (column.IsIdentity)
            sb.Append(" IDENTITY(1,1)");

        sb.Append(column.IsNullable ? " NULL" : " NOT NULL");

        return sb.ToString();
    }

    private static string FormatSqlType(SqlType type)
    {
        return type.StoreType switch
        {
            "nvarchar" or "varchar" or "char" or "nchar" or "varbinary" or "binary"
                => $"{type.StoreType}({(type.Length is null ? "max" : type.Length)})",

            "decimal" or "numeric"
                => $"{type.StoreType}({type.Precision ?? 18},{type.Scale ?? 0})",

            "datetime2" or "datetimeoffset" or "time"
                => type.Precision is not null
                    ? $"{type.StoreType}({type.Precision})"
                    : type.StoreType,

            _ => type.StoreType
        };
    }

    private static string FullTableName(string schema, string table)
        => $"{Bracket(schema)}.{Bracket(table)}";

    private static string FullColumnName(string schema, string table, string column)
        => $"{Bracket(schema)}.{Bracket(table)}.{Bracket(column)}";

    private static string Bracket(string value)
        => $"[{value}]";

    private static string EscapeSqlLiteral(string value)
        => value.Replace("'", "''");
}